# Generated by Django 3.2.3 on 2021-05-24 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ytid', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=800)),
                ('name', models.CharField(max_length=800)),
                ('created', models.DateTimeField(verbose_name='created date for given ytid')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(max_length=200)),
                ('selection_date', models.DateTimeField(verbose_name='date selection was made')),
                ('postingIP', models.CharField(max_length=200)),
                ('thumbnailOne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='bracket.thumbnail')),
                ('thumbnailTwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to='bracket.thumbnail')),
            ],
        ),
    ]
