FROM python:3.9

ENV DockerHome=/home/app/tmdwu
WORKDIR $DockerHome
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
RUN pip install --upgrade pip
COPY . ./
RUN pip install -r requirements.txt
RUN mkdir -p /mnt/videoMetadata
RUN mkdir -p /mnt/database
RUN rm -rf bracket/migrations
#EXPOSE 80
#EXPOSE 443
#EXPOSE 8000

#TODO: install cron and make sure cron file is copied to correct dir
    #Cron will run youtube-dl to metadata folder hourly
    #cron will run leaderboard refresh every minute

RUN apt-get update && apt-get install -y --no-install-recommends \
		cron \
        # package#2 \
	&& rm -rf /var/lib/apt/lists/*

#RUN python manage.py makemigrations
#RUN python manage.py migrate
#RUN python manage.py createcachetable

CMD python manage.py runserver 0.0.0.0:8000