FROM python:3.9

ENV DockerHome=/home/app/tmdwu
WORKDIR $DockerHome
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
RUN pip install --upgrade pip
COPY . ./
RUN pip install -r requirements.txt
RUN mkdir -p /mnt/videoMetadata
RUN mkdir -p /mnt/database
RUN rm -rf bracket/migrations
#EXPOSE 80
#EXPOSE 443
#EXPOSE 8000

#RUN python manage.py makemigrations
#RUN python manage.py migrate
CMD python manage.py runserver 0.0.0.0:8000